# ~/.config/starship.toml

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Inserts a blank line between shell prompts
add_newline = true

# Change command timeout from 500 to 1000 ms
command_timeout = 1000



format = """
$username\
[î‚°](bg:#1376f8 fg:#38ff9c)\
$directory\
$sudo\
[î‚°](bg:#fff383 fg:#1376f8)\
$time\
$cmd_duration\
$fill\ 
$env_var \ 
$shell\
$line_break\
$character"""





[username]
show_always = true
style_user = "bold fg:#000000 bg:#38ff9c"
style_root = "fg:#9A348E"
format = '[$user ]($style)'



[directory]
truncation_length = 2
truncation_symbol = "â€¦/"
home_symbol = " in ïŸ ~"
read_only_style = " blink fg:#ffffff bg:#1376f8"
read_only = " ï ½ "
format = "[$path]($style)[$read_only]($read_only_style)"
style = "bold fg:#ffffff bg:#1376f8"



[sudo]
style = "bold blink fg:#ffffff bg:#1376f8"
format = "[ $symbol]($style)"
symbol = "ïš¤ "
disabled = false
allow_windows = false


[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bold fg:#0b3b61 bg:#fff383"
format = "[ at î‹ $time ]($style)"

[cmd_duration]
min_time = 100
format = "[took $duration]($style) "
disabled = false
style = "bold fg:#0b3b61 bg:#fff383"


# Everything after this in the format array above, is Pushed to the right
[fill]
symbol = " "




# Shows an icon that should be included by zshrc script based on the distribution im on
[env_var.STARSHIP_DISTRO]
format = '[$env_value ]($style)'
style = "fg:#ff54b0"
variable = "STARSHIP_DISTRO"
disabled = false

[shell]
bash_indicator = "with î• BASH"
zsh_indicator = "with ïŒ¯ ZSH"
fish_indicator = "with ïœ¹ FISH"
powershell_indicator = "ï‘ _"
unknown_indicator = "mystery shell"
style = "bold fg:#ff54b0"
format = "[$indicator]($style) "
disabled = false

# Everything after this in the format array above, is in on a new line
[line_break]
disabled = false



# Change the default prompt characters
[character]
success_symbol = "[ ï˜  ï²’ ](bold #ff54b0)"
error_symbol = "[ï€ï€ï€ ï—  ï²’ ](bold #ae81ff)"
#success_symbol = ""
#error_symbol = ""


#[hostname]
#ssh_only = false
#style = "bold fg:#ffffff bg:#1376f8"
#format = '[$hostname]($style)'
#trim_at = "."
#disabled = false


# don't use because it doesn't show proton ip
#[localip]
#ssh_only = false
#format = "@ [$localipv4](bold red) "
#disabled = false

# don't use just to much info
#[memory_usage]
#disabled = false
#threshold = -1
#symbol = "îŠŒ  "
#style = "bold dimmed green"

# don't use wasn't working on laptop did not test very much 
#[battery]
#full_symbol = "ğŸ”‹ "
#charging_symbol = "âš¡ï¸ "
#discharging_symbol = "ğŸ’€ "
#disabled = false

####################### INCOPORTATE EVENTUALY ###################################
[git_branch]
symbol = "ï¡ "
format = "via [$symbol$branch]($style) "
# truncation_length = 4
truncation_symbol = "â€¦/"
style = "bold green"

[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "bold green"
conflicted = "ğŸ³"
up_to_date = "ï† "
untracked = "ï”© "
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
stashed = "ï£– "
modified = "ï„ "
staged = '[++\($count\)](green)'
renamed = "ïª¶ "
deleted = "ï€” "


[python]
symbol = "îˆµ "
pyenv_version_name = true

[lua]
format = "via [ğŸŒ• $version](bold blue) "


[nix_shell]
disabled = true
impure_msg = "[impure shell](bold red)"
pure_msg = "[pure shell](bold green)"
format = 'via [â˜ƒï¸ $state( \($name\))](bold blue) '